"use strict";
/**
 * The load-sensitive class names itself where a failure is read (task 153, obs #157, #166).
 *
 * A timing assertion that depends on machine load reads, when it goes red, exactly like a real
 * failure — so each trip was re-diagnosed from scratch, and on the v0.50.0 cut one aborted a
 * five-minute release run. Such assertions now build their message with `loadSensitive()` from
 * `shared/resources/spawn-budget.mjs`, and `docs/contributing/traps.md` § Load-sensitive tests is
 * the one list of files that do. Two directions hold the class together:
 *
 *   A. every wall-clock threshold assertion the enumeration pattern finds carries the marker — a new
 *      one added without it is red here;
 *   B. the set of files calling `loadSensitive(` equals the set traps.md lists — a file marked but
 *      not listed, or listed but no longer marked, is red here.
 *
 * Both scans exclude the bundled `skills/<skill>/references/` copies (regenerated by `npm run
 * bundle`, held equal to their source by `bundle:check`) and this guard, whose prose quotes the
 * shapes it scans for; B also excludes the module that defines the marker. Each direction has a non-vacuity floor: a scan that finds nothing
 * would otherwise pass for "everything is marked".
 *
 * The pattern sees `Date.now() - t0 < N` and `elapsed < N`. It does not see a timeout RACE such
 * as session-handoff CR-6; that one is held by its own unit tests in handoff-verify.test.js and
 * by direction B, which requires its file to be listed. Widen PATTERN here when a new spelling of
 * a wall-clock assertion appears.
 *
 * Run: node --test tests/load-sensitive-marker.test.js
 */
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { sectionOf } = require("./lib/markdown-section");

const REPO = path.join(__dirname, "..");
const PATTERN = "Date\\.now\\(\\) - [A-Za-z0-9_]+ *<|elapsed *<";
const PATHSPEC = ["*.test.js", "*.test.mjs", ":!skills/*/references/*"];
const DEFINER = "shared/resources/spawn-budget.mjs";
const SELF = "tests/load-sensitive-marker.test.js";
const TRAPS = path.join(REPO, "docs", "contributing", "traps.md");

function gitGrep(args) {
  // --untracked: a new test file is held before its first commit, not only after.
  const r = spawnSync(
    "git",
    ["grep", "--untracked", ...args, "--", ...PATHSPEC],
    {
      cwd: REPO,
      encoding: "utf8",
    },
  );
  // git grep exits 1 for "no match", which is an answer; anything else is a broken instrument.
  assert.ok(r.status === 0 || r.status === 1, `git grep failed: ${r.stderr}`);
  return r.stdout.split("\n").filter(Boolean);
}

/**
 * The text of the call that contains `line` (0-based): from the nearest `assert` at or above it
 * to the paren that closes it. Strings, templates and comments are skipped so a paren inside a
 * message does not end the call early — only code parens count.
 */
function enclosingAssert(lines, line) {
  let start = line;
  while (
    start >= 0 &&
    start > line - 6 &&
    !/\bassert(\.\w+)?\(/.test(lines[start])
  )
    start--;
  if (start < 0 || !/\bassert(\.\w+)?\(/.test(lines[start])) return null;
  const text = lines.slice(start, start + 40).join("\n");
  const from = text.search(/\bassert(\.\w+)?\(/);
  let depth = 0;
  let quote = null;
  for (let i = text.indexOf("(", from); i < text.length; i++) {
    const c = text[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") quote = c;
    else if (c === "(") depth++;
    else if (c === ")" && --depth === 0) return text.slice(from, i + 1);
  }
  return null;
}

test("direction A: every wall-clock threshold assertion carries the LOAD-SENSITIVE marker", () => {
  // This file quotes the pattern's shapes in its own prose and fixtures.
  const hits = gitGrep(["-nE", PATTERN]).filter(
    (h) => !h.startsWith(`${SELF}:`),
  );
  assert.ok(
    hits.length >= 4,
    `non-vacuity: the pattern found only ${hits.length} hit(s) — is the scan broken?`,
  );
  const unmarked = [];
  for (const hit of hits) {
    const [file, n] = hit.split(":");
    const lines = fs.readFileSync(path.join(REPO, file), "utf8").split("\n");
    const call = enclosingAssert(lines, Number(n) - 1);
    if (!call || !call.includes("loadSensitive("))
      unmarked.push(`${file}:${n}`);
  }
  assert.deepEqual(
    unmarked,
    [],
    "wall-clock assertion(s) without the marker — build the message with loadSensitive() " +
      "from spawn-budget.mjs and list the file in docs/contributing/traps.md § Load-sensitive tests",
  );
});

test("direction B: the files calling loadSensitive( are exactly the files traps.md lists", () => {
  const inCode = new Set(
    gitGrep(["-lF", "loadSensitive("]).filter(
      (f) => f !== DEFINER && f !== SELF,
    ),
  );
  const section = sectionOf(
    fs.readFileSync(TRAPS, "utf8"),
    "### Load-sensitive tests",
  );
  assert.ok(
    section,
    "docs/contributing/traps.md has no `### Load-sensitive tests` section",
  );
  const listed = new Set(
    section
      .map((l) => l.match(/^- `([^`]+)`\s*$/))
      .filter(Boolean)
      .map((m) => m[1]),
  );
  assert.ok(
    inCode.size >= 4,
    `non-vacuity: only ${inCode.size} file(s) call loadSensitive(`,
  );
  assert.ok(
    listed.size >= 4,
    `non-vacuity: traps.md lists only ${listed.size} file(s)`,
  );
  const unlisted = [...inCode].filter((f) => !listed.has(f)).sort();
  const stale = [...listed].filter((f) => !inCode.has(f)).sort();
  assert.deepEqual(
    unlisted,
    [],
    "marked in code but not listed in traps.md § Load-sensitive tests",
  );
  assert.deepEqual(
    stale,
    [],
    "listed in traps.md § Load-sensitive tests but no longer marked in code",
  );
});

test("enclosingAssert: a paren inside a message does not end the call early", () => {
  const lines = [
    "  assert.ok(",
    "    elapsed < 10,",
    "    `took (${elapsed}) ms`, loadSensitive(`x`),",
    "  );",
  ];
  assert.match(enclosingAssert(lines, 1), /loadSensitive\(/);
  assert.equal(enclosingAssert(["const x = elapsed < 3;"], 0), null);
});
