"use strict";
/**
 * The load-sensitive class names itself where a failure is read (task 153, obs #157, #166).
 *
 * A timing assertion that depends on machine load reads, when it goes red, exactly like a real
 * failure — so each trip was re-diagnosed from scratch, and on the v0.50.0 cut one aborted a
 * five-minute release run. Such assertions now build their message with `loadSensitive()` from
 * `shared/resources/spawn-budget.mjs`, and `docs/contributing/traps.md` § Load-sensitive tests is
 * the one list of files that do. Two directions hold the class together:
 *
 *   A. every wall-clock threshold assertion the enumeration pattern finds carries the marker — a new
 *      one added without it is red here;
 *   B. the set of files calling `loadSensitive(` equals the set traps.md lists — a file marked but
 *      not listed, or listed but no longer marked, is red here;
 *   C. every test file that reads a HIGH-RESOLUTION clock (`process.hrtime`, `performance.now`)
 *      carries the marker — those clocks exist only to time things, so this is the enumeration by
 *      clock source that A's spelling-based pattern cannot be (QA cycle 2, CR2-1: three
 *      `ms < FILE_BUDGET_MS` whole-file budgets were invisible to A). `Date.now()` is not in C:
 *      it also drives deadlines and poll loops, which are not assertions.
 *
 * Both scans exclude the bundled `skills/<skill>/references/` copies (regenerated by `npm run
 * bundle`, held equal to their source by `bundle:check`) and this guard, whose prose quotes the
 * shapes it scans for. The module that defines the marker needs no exclusion: the pathspec reads
 * test files only, and it is not one. Each direction has a non-vacuity floor: a scan that finds nothing
 * would otherwise pass for "everything is marked".
 *
 * The pattern sees `Date.now() - t0 < N`, `elapsed < N` and `ms < …BUDGET…`. It does not see a timeout RACE such
 * as session-handoff CR-6; that one is held by its own unit tests in handoff-verify.test.js and
 * by direction B, which requires its file to be listed. Widen PATTERN here when a new spelling of
 * a wall-clock assertion appears.
 *
 * Run: node --test tests/load-sensitive-marker.test.js
 */
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const { sectionOf } = require("./lib/markdown-section");

const REPO = path.join(__dirname, "..");
const PATTERN =
  "Date\\.now\\(\\) - [A-Za-z0-9_]+ *<|elapsed *<|(^|[^A-Za-z0-9_])ms *< *[A-Z_]*BUDGET";
const HIRES_CLOCK = "process\\.hrtime|performance\\.now";
const PATHSPEC = ["*.test.js", "*.test.mjs", ":!skills/*/references/*"];
const SELF = "tests/load-sensitive-marker.test.js";
const TRAPS = path.join(REPO, "docs", "contributing", "traps.md");

function gitGrep(args) {
  // --untracked: a new test file is held before its first commit, not only after.
  const r = spawnSync(
    "git",
    ["grep", "--untracked", ...args, "--", ...PATHSPEC],
    {
      cwd: REPO,
      encoding: "utf8",
    },
  );
  // git grep exits 1 for "no match", which is an answer; anything else is a broken instrument.
  assert.ok(r.status === 0 || r.status === 1, `git grep failed: ${r.stderr}`);
  return r.stdout.split("\n").filter(Boolean);
}

/**
 * The text of the call that contains the hit at `line`, `col` (both 0-based): from the nearest
 * `assert` at or above it to the paren that closes it — or null when the hit is not between the
 * call's opening and its closing paren (a bare `const ok = elapsed < N;` under, or after on the
 * same line as, a marked assert is not marked; QA cycle 1 CR-1, cycle 2 CR2-3). String and template contents are skipped so a paren inside a message does not
 * end the call early. Comments are not skipped: a quote character in a comment inside the call
 * would misread it, which errs toward "unmarked" — a red, never a false green.
 */
function enclosingAssert(lines, line, col = 0) {
  let start = line;
  while (
    start >= 0 &&
    start > line - 6 &&
    !/\bassert(\.\w+)?\(/.test(lines[start])
  )
    start--;
  if (start < 0 || !/\bassert(\.\w+)?\(/.test(lines[start])) return null;
  const text = lines.slice(start, start + 40).join("\n");
  const from = text.search(/\bassert(\.\w+)?\(/);
  let hit = col;
  for (let k = start; k < line; k++) hit += lines[k].length + 1;
  let depth = 0;
  let quote = null;
  for (let i = text.indexOf("(", from); i < text.length; i++) {
    const c = text[i];
    if (quote) {
      if (c === "\\") i++;
      else if (c === quote) quote = null;
      continue;
    }
    if (c === '"' || c === "'" || c === "`") quote = c;
    else if (c === "(") depth++;
    else if (c === ")" && --depth === 0) {
      return hit < from || hit > i ? null : text.slice(from, i + 1);
    }
  }
  return null;
}

test("direction A: every wall-clock threshold assertion carries the LOAD-SENSITIVE marker", () => {
  // This file quotes the pattern's shapes in its own prose and fixtures.
  const hits = gitGrep(["-n", "--column", "-E", PATTERN]).filter(
    (h) => !h.startsWith(`${SELF}:`),
  );
  assert.ok(
    hits.length >= 7,
    `non-vacuity: the pattern found only ${hits.length} hit(s) — is the scan broken?`,
  );
  const unmarked = [];
  for (const hit of hits) {
    const [file, n, c] = hit.split(":");
    const lines = fs.readFileSync(path.join(REPO, file), "utf8").split("\n");
    const call = enclosingAssert(lines, Number(n) - 1, Number(c) - 1);
    if (!call || !call.includes("loadSensitive("))
      unmarked.push(`${file}:${n}`);
  }
  assert.deepEqual(
    unmarked,
    [],
    "wall-clock assertion(s) without the marker — build the message with loadSensitive() " +
      "from spawn-budget.mjs and list the file in docs/contributing/traps.md § Load-sensitive tests",
  );
});

test("direction B: the files calling loadSensitive( are exactly the files traps.md lists", () => {
  const inCode = new Set(
    gitGrep(["-lF", "loadSensitive("]).filter((f) => f !== SELF),
  );
  const section = sectionOf(
    fs.readFileSync(TRAPS, "utf8"),
    "### Load-sensitive tests",
  );
  assert.ok(
    section,
    "docs/contributing/traps.md has no `### Load-sensitive tests` section",
  );
  const listed = new Set(
    section
      .map((l) => l.match(/^- `([^`]+)`\s*$/))
      .filter(Boolean)
      .map((m) => m[1]),
  );
  assert.ok(
    inCode.size >= 4,
    `non-vacuity: only ${inCode.size} file(s) call loadSensitive(`,
  );
  assert.ok(
    listed.size >= 4,
    `non-vacuity: traps.md lists only ${listed.size} file(s)`,
  );
  const unlisted = [...inCode].filter((f) => !listed.has(f)).sort();
  const stale = [...listed].filter((f) => !inCode.has(f)).sort();
  assert.deepEqual(
    unlisted,
    [],
    "marked in code but not listed in traps.md § Load-sensitive tests",
  );
  assert.deepEqual(
    stale,
    [],
    "listed in traps.md § Load-sensitive tests but no longer marked in code",
  );
});

test("direction C: every test file reading a high-resolution clock carries the marker (CR2-1)", () => {
  const clockFiles = gitGrep(["-lE", HIRES_CLOCK]).filter((f) => f !== SELF);
  const marked = new Set(gitGrep(["-lF", "loadSensitive("]));
  assert.ok(
    clockFiles.length >= 1,
    `non-vacuity: no test file reads process.hrtime / performance.now — is the scan broken?`,
  );
  assert.deepEqual(
    clockFiles.filter((f) => !marked.has(f)).sort(),
    [],
    "reads a high-resolution clock but builds no message with loadSensitive() — mark the timing " +
      "assertion and list the file in docs/contributing/traps.md § Load-sensitive tests",
  );
});

test("enclosingAssert: a paren inside a message does not end the call early", () => {
  const lines = [
    "  assert.ok(",
    "    elapsed < 10,",
    "    `took (${elapsed}) ms`, loadSensitive(`x`),",
    "  );",
  ];
  assert.match(enclosingAssert(lines, 1), /loadSensitive\(/);
  assert.equal(enclosingAssert(["const x = elapsed < 3;"], 0), null);
});

test("enclosingAssert: a comparison below a marked assert, outside any call, is not credited to it (CR-1)", () => {
  const lines = [
    "  assert.ok(x < 1, loadSensitive(`marked`));",
    "  const ok = Date.now() - t0 < 100;",
    '  assert.ok(ok, "plain");',
  ];
  assert.equal(
    enclosingAssert(lines, 1),
    null,
    "the marked call above closes before the hit",
  );
  // and the hit inside a multi-line marked call is still credited
  // a hit on the SAME line, after a marked call has closed, is not credited either (CR2-3)
  const same = ['  assert.ok(a, loadSensitive("x")); const ok = elapsed < 5;'];
  assert.equal(enclosingAssert(same, 0, same[0].indexOf("elapsed")), null);
  assert.match(
    enclosingAssert(same, 0, same[0].indexOf("a,")),
    /loadSensitive\(/,
  );
  const inside = [
    "  assert.ok(",
    "    Date.now() - t0 < 100,",
    "    loadSensitive(`m`),",
    "  );",
  ];
  assert.match(enclosingAssert(inside, 1), /loadSensitive\(/);
});
